"""국가명 영문 -> 한글 표시용 정적 매핑.

AI 호출 없이 화면 표시에만 쓰는 딕셔너리. country 자체는 DB에 크롤링된
영문 원문 그대로 저장하고, 화면에 보여줄 때만 이 매핑으로 변환한다
(매핑에 없는 국가명은 원문을 그대로 보여준다)."""

COUNTRY_KO = {
    "Afghanistan": "아프가니스탄",
    "Albania": "알바니아",
    "Algeria": "알제리",
    "Andorra": "안도라",
    "Angola": "앙골라",
    "Argentina": "아르헨티나",
    "Armenia": "아르메니아",
    "Australia": "호주",
    "Austria": "오스트리아",
    "Azerbaijan": "아제르바이잔",
    "Bahamas": "바하마",
    "Bahrain": "바레인",
    "Bangladesh": "방글라데시",
    "Barbados": "바베이도스",
    "Belarus": "벨라루스",
    "Belgium": "벨기에",
    "Belize": "벨리즈",
    "Benin": "베냉",
    "Bhutan": "부탄",
    "Bolivia": "볼리비아",
    "Bosnia and Herzegovina": "보스니아 헤르체고비나",
    "Botswana": "보츠와나",
    "Brazil": "브라질",
    "Brunei": "브루나이",
    "Bulgaria": "불가리아",
    "Burkina Faso": "부르키나파소",
    "Burundi": "부룬디",
    "Cambodia": "캄보디아",
    "Cameroon": "카메룬",
    "Canada": "캐나다",
    "Cape Verde": "카보베르데",
    "Central African Republic": "중앙아프리카공화국",
    "Chad": "차드",
    "Chile": "칠레",
    "China": "중국",
    "Colombia": "콜롬비아",
    "Comoros": "코모로",
    "Costa Rica": "코스타리카",
    "Croatia": "크로아티아",
    "Cuba": "쿠바",
    "Cyprus": "키프로스",
    "Czech Republic": "체코",
    "Czechia": "체코",
    "Democratic Republic of the Congo": "콩고민주공화국",
    "Denmark": "덴마크",
    "Djibouti": "지부티",
    "Dominica": "도미니카",
    "Dominican Republic": "도미니카공화국",
    "Ecuador": "에콰도르",
    "Egypt": "이집트",
    "El Salvador": "엘살바도르",
    "Equatorial Guinea": "적도기니",
    "Eritrea": "에리트레아",
    "Estonia": "에스토니아",
    "Eswatini": "에스와티니",
    "Ethiopia": "에티오피아",
    "Fiji": "피지",
    "Finland": "핀란드",
    "France": "프랑스",
    "Gabon": "가봉",
    "Gambia": "감비아",
    "Georgia": "조지아",
    "Germany": "독일",
    "Ghana": "가나",
    "Greece": "그리스",
    "Grenada": "그레나다",
    "Guatemala": "과테말라",
    "Guinea": "기니",
    "Guinea-Bissau": "기니비사우",
    "Guyana": "가이아나",
    "Haiti": "아이티",
    "Honduras": "온두라스",
    "Hong Kong": "홍콩",
    "Hungary": "헝가리",
    "Iceland": "아이슬란드",
    "India": "인도",
    "Indonesia": "인도네시아",
    "Iran": "이란",
    "Iraq": "이라크",
    "Ireland": "아일랜드",
    "Israel": "이스라엘",
    "Italy": "이탈리아",
    "Ivory Coast": "코트디부아르",
    "Cote d'Ivoire": "코트디부아르",
    "Jamaica": "자메이카",
    "Japan": "일본",
    "Jordan": "요르단",
    "Kazakhstan": "카자흐스탄",
    "Kenya": "케냐",
    "Kiribati": "키리바시",
    "Kosovo": "코소보",
    "Kuwait": "쿠웨이트",
    "Kyrgyzstan": "키르기스스탄",
    "Laos": "라오스",
    "Latvia": "라트비아",
    "Lebanon": "레바논",
    "Lesotho": "레소토",
    "Liberia": "라이베리아",
    "Libya": "리비아",
    "Liechtenstein": "리히텐슈타인",
    "Lithuania": "리투아니아",
    "Luxembourg": "룩셈부르크",
    "Macau": "마카오",
    "Madagascar": "마다가스카르",
    "Malawi": "말라위",
    "Malaysia": "말레이시아",
    "Maldives": "몰디브",
    "Mali": "말리",
    "Malta": "몰타",
    "Marshall Islands": "마셜제도",
    "Mauritania": "모리타니",
    "Mauritius": "모리셔스",
    "Mexico": "멕시코",
    "Micronesia": "미크로네시아",
    "Moldova": "몰도바",
    "Monaco": "모나코",
    "Mongolia": "몽골",
    "Montenegro": "몬테네그로",
    "Morocco": "모로코",
    "Mozambique": "모잠비크",
    "Myanmar": "미얀마",
    "Namibia": "나미비아",
    "Nauru": "나우루",
    "Nepal": "네팔",
    "Netherlands": "네덜란드",
    "New Zealand": "뉴질랜드",
    "Nicaragua": "니카라과",
    "Niger": "니제르",
    "Nigeria": "나이지리아",
    "North Korea": "북한",
    "North Macedonia": "북마케도니아",
    "Norway": "노르웨이",
    "Oman": "오만",
    "Pakistan": "파키스탄",
    "Palau": "팔라우",
    "Palestine": "팔레스타인",
    "Panama": "파나마",
    "Papua New Guinea": "파푸아뉴기니",
    "Paraguay": "파라과이",
    "Peru": "페루",
    "Philippines": "필리핀",
    "Poland": "폴란드",
    "Portugal": "포르투갈",
    "Qatar": "카타르",
    "Republic of the Congo": "콩고공화국",
    "Romania": "루마니아",
    "Russia": "러시아",
    "Rwanda": "르완다",
    "Saint Kitts and Nevis": "세인트키츠 네비스",
    "Saint Lucia": "세인트루시아",
    "Saint Vincent and the Grenadines": "세인트빈센트 그레나딘",
    "Samoa": "사모아",
    "San Marino": "산마리노",
    "Sao Tome and Principe": "상투메 프린시페",
    "Saudi Arabia": "사우디아라비아",
    "Senegal": "세네갈",
    "Serbia": "세르비아",
    "Seychelles": "세이셸",
    "Sierra Leone": "시에라리온",
    "Singapore": "싱가포르",
    "Slovakia": "슬로바키아",
    "Slovenia": "슬로베니아",
    "Solomon Islands": "솔로몬제도",
    "Somalia": "소말리아",
    "South Africa": "남아프리카공화국",
    "South Korea": "한국",
    "Korea, South": "한국",
    "Korea": "한국",
    "South Sudan": "남수단",
    "Spain": "스페인",
    "Sri Lanka": "스리랑카",
    "Sudan": "수단",
    "Suriname": "수리남",
    "Sweden": "스웨덴",
    "Switzerland": "스위스",
    "Syria": "시리아",
    "Taiwan": "대만",
    "Tajikistan": "타지키스탄",
    "Tanzania": "탄자니아",
    "Thailand": "태국",
    "Timor-Leste": "동티모르",
    "Togo": "토고",
    "Tonga": "통가",
    "Trinidad and Tobago": "트리니다드 토바고",
    "Tunisia": "튀니지",
    "Turkey": "튀르키예",
    "Turkmenistan": "투르크메니스탄",
    "Tuvalu": "투발루",
    "Uganda": "우간다",
    "Ukraine": "우크라이나",
    "United Arab Emirates": "아랍에미리트",
    "United Kingdom": "영국",
    "UK": "영국",
    "United States": "미국",
    "United States of America": "미국",
    "USA": "미국",
    "US": "미국",
    "Uruguay": "우루과이",
    "Uzbekistan": "우즈베키스탄",
    "Vanuatu": "바누아투",
    "Vatican City": "바티칸",
    "Venezuela": "베네수엘라",
    "Vietnam": "베트남",
    "Yemen": "예멘",
    "Zambia": "잠비아",
    "Zimbabwe": "짐바브웨",
}


def to_korean(country_en):
    """매핑에 없으면 원문(영문)을 그대로 반환 — 절대 빈 값이나 에러를 내지 않는다."""
    if not country_en:
        return country_en
    return COUNTRY_KO.get(country_en.strip(), country_en)
